version: "3.8"

services:
  # docker run -d --rm --name mongo -p 27017:27017 -v mongodbdata:/data/db mongo
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017 # external:internal (ports)
    volumes:
      - mongodbdata:/data/db

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq

volumes:
  mongodbdata:
  rabbitmqdata:
